version: '3'
services:
  app:
    build: .
    # working_dir: "/app"
    tty: true
    stdin_open: true
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./downloads:/home/pptruser/Downloads
    shm_size: 512 # 一時ファイル領域(MB)
